name: Deploy development

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions/upload-artifact@v4
        with:
          name: pushkind-files
          path: ./target/release/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v4
        with:
          name: pushkind-files
          path: ./target/release/pushkind-files
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CICD_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.CICD_KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      - name: Deploy
        run: |
          ssh cicd@images.pushkind.com "supervisorctl stop files"
          scp ./target/release/pushkind-files cicd@images.pushkind.com:/var/www4/html/
          scp -r ./assets/ cicd@images.pushkind.com:/var/www4/html/
          scp -r ./templates/ cicd@images.pushkind.com:/var/www4/html/
          ssh cicd@images.pushkind.com "cd /var/www4/html/ && supervisorctl start files"
